name: iOS
permissions:
  contents: read

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ macos-12, macos-13 ]
    steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - uses: lukka/get-cmake@28983e0d3955dba2bb0a6810caae0c6cf268ec0c # v4.0.0
        - name: Download dependencies
          run: python3 utils/git-sync-deps
        # NOTE: The MacOS SDK ships universal binaries. CI should reflect this.
        - name: Configure Universal Binary for iOS
          run: |
            cmake -S . -B build \
            -D CMAKE_BUILD_TYPE=Debug \
            -D CMAKE_SYSTEM_NAME=iOS \
            "-D CMAKE_OSX_ARCHITECTURES=arm64;x86_64" \
            -G Ninja
          env:
            # Linker warnings as errors
            LDFLAGS: -Wl,-fatal_warnings
        - run: cmake --build build
        - run: cmake --install build --prefix /tmp
